### PR TITLE
Implement full bash parsing

### PR DESCRIPTION
**Pull request by jacob-pro**
This completes the TODO item: `todo this should perform a more sophisticated bash parsing` so that quotes and other special characters are now properly handled.

This is based on code from the https://github.com/tmiasko/shell-words crate (also Apache 2.0 licensed), with the following modifications:

- Allows unfinished / partial shell commands, e.g. unclosed quote marks
- Tracks the index of the current word and current character within that word.

- [X] Unit tests included

### CODE REVIEW

**Comment by jacob-pro** [comment]
hey @JoshMcguigan 
would you be willing to accept a PR like this?
are there any changes you would like to see?
Thanks :)

**Comment by JoshMcguigan** [comment]
Thanks so much for the PR! I really appreciate the unit tests!

**Comment by jacob-pro** [comment]
Hey @JoshMcguigan 
Please could this version be published to crates.io ?

**Comment by JoshMcguigan** [comment]
Published to crates.io as 0.1.0. Thanks again for the contribution!

**Pull request merged**
